inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - .git/**/*
    - files/**/*
    - templates/**/*
    - etc/**/*
    - vendor/**/*

Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - test/**/*
Metrics/ParameterLists:
  Enabled: false
Metrics/CyclomaticComplexity:
  Severity: warning
  Max: 20
Metrics/PerceivedComplexity:
  Severity: warning
  Max: 20
Metrics/BlockNesting:
  Severity: warning
  Max: 4
Metrics/AbcSize:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - lib/fakefs/file.rb
Naming/MethodName:
  Enabled: false

Security/Eval:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TrivialAccessors:
  ExactNameMatch: true
