language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.0
  - 2.3.1
  - 2.4.1
  - 2.5.0
  - ruby-head
  - jruby-1.7.27
  - jruby-9.1.13.0
  - jruby-head
env:
  matrix:
    - TASK=test
    - TASK=spec
    - TASK=rubocop
matrix:
  allow_failures:
    - rvm: jruby-1.7.27
    - rvm: jruby-9.1.13.0
    - rvm: jruby-head
before_install:
  - gem --version
  - gem install bundler
script: bundle exec rake $TASK
